Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.33.101"
  config.vm.provider "virtualbox" do |vb|
	vb.memory=4096
  end
  config.vm.box_download_insecure = true
  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: "/vagrant/modules/docker-compose.yml", run: "always"
  config.vm.provision :shell, path: "./install.sh" 
end